const se = (e: any, r: any) => {
  let l = '';
  for (let t = 0; t < e.length; t++) l += String.fromCharCode(e.charCodeAt(t) ^ r);
  return l;
};

const xx = (t: any, e: any, r: any) => {
  for (var l = se(btoa(r), 10), o = [], n = -1, a = 0; a < t.length; a++) {
    var h = Math.floor(a / l.length + 1),
      s = a >= l.length ? a % l.length : a,
      h = l.charCodeAt(s) * l.charCodeAt(h);
    n < h && (n = h);
  }
  for (var i = 0; t.length > i; i++) {
    var c = Math.floor(i / l.length) + 1,
      f = i % l.length,
      g = l.charCodeAt(f) * l.charCodeAt(c);
    for (e <= g && (g = Math.floor((+g / +n) * (e - 1) + 0)); -1 !== o.indexOf(g); ) g += 1;
    o.push(g);
  }
  return o.sort(function (t, e) {
    return t - e;
  });
};

const us = (e: any, t: any, r: any) => {
  var l = se(btoa(t), 10),
    o = xx(l, e.length - 20, r);
  let n: any[] = [],
    a = 0;
  for (let t = 0; t < l.length; t++) {
    var h = o[t] - t - a;
    n.splice(a, 0, ...e.slice(0, h)), (e = e.slice(h)), (a = o[t] - t - 1);
  }
  return n.join('').slice(0, -l.length) + e;
};

const parse = (t: string) => {
  const parsed = JSON.parse(
    se(atob(us(t.split('payload=')[1].split('&')[0], '1604064986000', t.split('uuid=')[1].split('&')[0])), 50)
  );

  const steps: any = {};

  parsed.forEach((p: { t: any; d: any }) => {
    steps[p.t] = p.d;
  });

  return steps;
};

export type PXPayload = {
  [step: string]: string[];
};

export function ParsePayload(payload: string): PXPayload | null {
  try {
    const parsedPayload: PXPayload = parse(payload);

    console.log(parsedPayload);

    return Object.keys(parsedPayload).length === 0 ? null : parsedPayload;
  } catch (e) {
    return console.error(e), null;
  }
}

// payload=aUkQRhAIEGJqAwIBAgEQHhBWEAhJEGJqAwILAAsQCAIeEGJqAwIABgoQCAAeEGJqAwIFAgcQCBBmS0JXd0BAXUAIEnFTXFxdRhJAV1NWEkJAXUJXQEZbV0ESXVQSXEdeXhIaQFdTVltcVRIVAhUbblwSEhISU0YSYUYSGlpGRkJBCB0dRUVFHEFBV1xBVxxRXV8dBwpzQUQBBwsdW1xbRhxYQQgACAMBAQAHG25cEhISElNGEl5cEhpaRkZCQQgdHUVFRRxBQVdcQVccUV1fHQcKc0FEAQcLHVtcW0YcWEEIAAgBAgMDAxtuXBISEhJTRhJdXBIaWkZGQkEIHR1FRUUcQUFXXEFXHFFdXx0HCnNBRAEHCx1bXFtGHFhBCAAIAAsDAwMbblwSEhISU0YSWkZGQkEIHR1FRUUcQUFXXEFXHFFdXx0HCnNBRAEHCx1bXFtGHFhBCAAIAAoEBgEQHhBiagMCAQQCEAgQWkZGQkEIHR1FRUUcQUFXXEFXHFFdXx1XXB9aQBAeEGJqAwIBAwMQCGlvHhBiagMCBQYGEAgQEB4QYmoDAgIGBBAIVFNeQVceEGJqAwIHBAMQCAYCCwQeEGJqAwIGCwsQCAMDBwAeEGJqAwIKBgEQCAYCAQYeEGJqAwIKBwIQCAMDBwAeEGJqAwMDAwEQCBAGAgsEagMDBwAQHhBiagMCBQAGEAgABh4QYmoDAgIKCxAIAAYeEGJqAwIAAgYQCAACAwseEGJqAwMDAQoQCAMCBgAeEGJqAwMDBQIQCAIeEGJqAwMDBQYQCAIeEGJqAwIABgEQCEZAR1ceEGJqAwICAwIQCFRTXkFXHhBiagMCAAAHEAhUU15BVx4QYmoDAgoHBxAIVFNeQVceEGJqAwMCBAcQCFRTXkFXHhBiagMCBgcEEAhUU15BVx4QYmoDAgYGAxAIVFNeQVceEGJqAwICCwoQCFRTXkFXHhBiagMCBwcFEAhUU15BVx4QYmoDAgMFAhAIVFNeQVceEGJqAwIKAAYQCFRTXkFXHhBiagMCAgoFEAhUU15BVx4QYmoDAwIGABAIVFNeQVceEGJqAwMCBwcQCBADBgZOBAROBAROAwUATgoCEB4QYmoDAgYAABAIAwsBHhBiagMCBAcLEAhGQEdXHhBiagMCAQMEEAhGQEdXHhBiagMCBQYAEAgQVFNeQVcQHhBiagMDAwYKEAgQVFNeQVcQHhBiagMCCgYEEAgDHhBiagMCAQABEAgDHhBiagMDAgMHEAgQEB4QYmoDAgcLCxAIaRBeXVNWZltfV0EQHhBRQVsQHhBTQkIQHhBAR1xGW19XEG8eEGJqAwIABgsQCBAEBgcHBFEFBRAeEGJqAwIAAQoQCBAQHhBiagMCCwsHEAgQAwIAAgVQAFQQHhBiagMCBwQFEAgQAwIAAgVQAFQQHhBiagMDAwsAEAgQCwJXBAcGBAcQHhBiagMCAgQHEAhGQEdXHhBiagMDAwcBEAhGQEdXHhBiagMCBwILEAhGQEdXHhBiagMCAAAFEAhGQEdXHhBiagMCAwYDEAgDBAYGAwMBBAsDBAYBHhBiagMCBgMKEAgQAwMLCwEACwMFAAYGBAQHAgIEBQAQHhAGBg4OBAUOBgAFAwMBAQIHBwEABRAIEAcHDw8FBA8HAQQCAgAAAwYGAAEEEB4QYmoDAwMKAxAICwYHBB4QYmoDAgcAABAIEAsHBVEGAFMBUwMGUQNUCwVXClELCgUABQZUUwEHAlBWEB4QYmoDAgoGAhAIEFEFRFtHBEQEXgIKXlpUXQFYVF9VEB4QYmoDAgYEBhAIEFEAA1FRVwAAAwoFUwYBUQoBAQVWC1QGAgMLUFQFBQQDEB4QYmoDAgIKAhAIEAALA1FTB1dTA1RXClAGVAoBAQtRBlAEC1FQBwoEUwQHEB4QYmoDAgULAhAIaRBidnQSZFtXRVdAEB4QcVpAXV9XEmJ2dBJkW1dFV0AQHhBxWkBdX1tHXxJidnQSZFtXRVdAEB4Qf1tRQF1BXVRGEndWVVcSYnZ0EmRbGV0VXQBAeEGVXUHlbRhJQR1teRh9bXBJidn^QQbx4QYmoDAwIDAhAIBx4QYmoDAgAKCxAIRkBHVx4QYmoDAwIGARAIRkBHVx4QYmoDAgILARAIRkBHVx4QYmoDAgQCBhAIRkBHVx4QYmoDAgALBBAIEFdcH2dhEB4QYmoDAwMKBBAIEGVbXAEAEB4QYmoDAgELBRAIaRBXXB9nYRBvHhBiagMCBgUAEAgQf11IW15eUx0HHAISGmVbXFZdRUESfGYSAwIcAgkSZVtcBAYJEkoEBhsSc0JCXldlV1B5W0YdBwEFHAEEEhp5emZ/fh4SSXltZVxJ1V1FZXRsScVpAXV9XHQsFHAIcB:gQLABwLCxJhU1RTQFsdBwEFHAEEEB4QYmoDNDAgUHChAIRkBHVx4QYmoDAgILCxAIHwQCHhBiagMCAQEEEAgKHhBiagMCAQUBEAgDHhBOiagMCCgIAEAgQdVdRWV0QHhBiagMCBAAKEAgQAAICAQIDAgUQHhBiagMDAgELEAgQBxwCEhplW1xWXUVBEnxmEgMCHAIJEmVbXAQGCRJKBAYbEnNCQl5XZVdQeVtGHQcBBRwBBBIaeXprGmf34eEl5bWVcSdVdRWV0bEnFaQF1fVx0LBRwCHAYECwAcCwsSYVNUU0BbHQcBBRwBBBAeEGJqAwIHBgUQCEZAR1ceEGJqAwIDBQYQCEpZAR1ceEGJqAwIFBQcQCAAeEGJqAwIHAQsQCBB8V0ZBUVNCVxAeEGJqAwIDCgsQCBB/XUhSbXl5TEB4QYmoDAgELAhAIRkBHVx4QYmoDAgsEARAIBwIeEGJqAwICCgMQCFRTXkFXHhBiagMCAQsLEAgDAh4QYmoDAgAFARAIEAZVEB4Q?YmoDAgcLBxAIRkBHVx4QYmoDAgoAABAIRkBHVx4QYmoDAwICABAIRkBHVx4QYmoDAgYDAhAIVFNeQVceEGJqAwMCAwoQCFRTXkFXHhBiagMCAAMKEAgQVwJXU1QDAlcQHhBiagMCAwQAEAgQBVYECgpQA1AQHhBiagMCCwYCEAgQBQUEBFMHAFYQHhBiagMDAAILEAgQAwoCVlYFVwEQHhBiagMCBgsKEAgQBFMLAgEFClYQHhBiagMCAAELEAgDCwsCAwMGAB4QYmoDAgAEBRAIBgALBgUCBwMHAB4QYmoDAgcHAxAIAAUCBQUGAAQeEGJqAwIHBwoQCBBhR1wSdFdQEgIEEgACAAASAgEIAwYIBwISdX9mGQIDAgISGnFXXGEZAU14Sd0dAXUJXU1wSYUZTXFZTQFYSZltfVxsQHhBiagMCAAEEEAhUU15BVx4QYmoDAgYCAhAIVFNeQVceEGJqAwIHAQIQCFRTXkFXHhBiagMDAgQCEAhGQEdXHhBiagMCCgIDEAgDAh4QYmoDAgELBhAIRkBHVx4QYmoDAgIHChAI^EERbQVtQXlcQHhBiagMDAwABEAhUU15BVx4QYmoDAgILBBAIAh4QYmoDAgoFABAIAAIBBh4QYmoDAwIAChAIRkBHVx4QYmoDAgEEBBAIAwMEAx4QYmoDAgcKBxAIEF9bQUFbXFUQHhBSiagMCCwUEEAhGQEdXHhBiagMCAAcCEAhGQEdXHhBiagMCAAcLEAhUU15BVx4QYmoDAgMHBBAIRkBHVx4QYmoDAgUDABAIAx4QYmoDAgcHBxAIAQceEGJqAwIBBgUQCAEeEGJqAwIDAwsQCAIeEGJqAwIKCwMQCAMeEGJqAwIEAAAQCAMeEGJqAwIABQAQCAMLAQMeEGJqAwICBgMQCAMEBgYDAwEECwIKBgEeEGJqAwILBQIQCAEEAgIeEGJqAwICCwYQCAMEBgYDAwEECwIBBQseEGJqAwMCAgYQCAMEBgYDAwEECwMHBgQeEGJ:GqAwIAAgQQCBALAgcFAABRAh8KBFQAHwMDV1EfCgcKAR8AVgNWBAsBU1MKBwoQHhBiagM}CAgoKEAhGQEdXT08eSRBGEAgQYmoDAgQGB7BAeEFYQCEkQYmoDAgQKChAIEAZUVgELBgMHEB4QYmoDAwMBARAIAh4QYmoDAgADBxAIEAMCUFcDVlcHEB4QYmoDAgUEAhAIAh4QYmoDAgEDBhAIEFEKAAMHAwVQEB4QYmoDAgMBBBAIAh4QYmoDAgADBBAIEANRAQFWCgcEEB4QYmoDAgUBBRAIRkBHVx4QYmoDAgEACxAIAh4QYmoDAgQGBxAIEFYFBwsDAwZUEB4QYmoDAgQEARAIAh4QYmoDAgQAABAIAB4QYmoDAgAFABAIAwsKCx4QYmoDAwICBhAIAwQGBgMDAQQLAwcGBB4QYmoDAgACBBAIEAsCBwUAAFECHwoEVAAfAwNXUR8KBwoBHwBWA1YECwFTUwoHChAeEGJ7qAwICCgoQCEZAR1dPT28=&appId=PX58Asv359&tag=v7.3.5&uuid=905722c0-86f2-11ec-8583-2d1d693aa858&ft=248&seq=1&en=NTA&cs=0948b913f910da83fbaf3e11e75ae10c8207016c7bbc109559b29808461bb707&pc=7340489770091289&sid=911a4bb0-86f2-11ec-bfb7-372b8a6fb8b7ó ±ó ¶ó ´ó ´ó ±ó ±ó ³ó ¶ó ¹ó ±ó ¶ó ´ó ³&vid=90578869-86f2-11ec-bc6a-595050534663&pxhd=rmOADVw90Jy5j-8QO0UOfgC1DavciR5CIS78XnTLIza7yaFWCqOhRDcVRyeJRnZrVPiBv1L7PdtHqDcDbcu5zg==:L/PniGxHZVzy2uoixJrUC4T-DTBSV3lHeVoKLEEVgeRRSelsE9vZpoTXHDXH2k1/Kjxge71K2rDyWFbMqtybrXqZExidzis4bChpLbKrvQY=&cts=911a99d0-86f2-11ec-bfb7-372b8a6fb8b7&rsc=2